name: 1Password
description: Exports secrets from 1Password vault(s)

inputs:
  secrets:
    description: 'Secrets references in KEY=VALUE format, one per line'
    required: true

  op-service-account-token:
    description: '1Password service account token with access to the vault(s)'
    required: true

  op-env-file:
    description: 'Path to template .env file for secrets injection'
    required: false

  op-export-env:
    description: 'Whether to export secrets as environment variables'
    required: false
    default: 'true'

outputs:
  secrets:
    description: 'Exported secrets mapped to their values as a JSON string'
    value: ${{ toJSON(steps.load-secrets.outputs) }}

runs:
  using: composite
  steps:
    - name: Export secret references to GITHUB_ENV
      shell: bash
      # language=bash
      run: |
        echo "${{ inputs.secrets }}" >> $GITHUB_ENV

    - name: Export secrets from 1Password vault(s)
      id: load-secrets
      uses: 1password/load-secrets-action@v4
      with:
        export-env: ${{ inputs.op-export-env }}
      env:
        OP_SERVICE_ACCOUNT_TOKEN: ${{ inputs.op-service-account-token }}
        OP_ENV_FILE: ${{ inputs.op-env-file }}
