allowBuilds:
  '@swc/core': true
  unrs-resolver: true

autoInstallPeers: false

enablePrePostScripts: true

engineStrict: true

minimumReleaseAge: 1140

saveExact: true

strictPeerDependencies: true
