name: Create release tags
description: Creates Git tags for the new release based on the Changesets versioning

inputs:
  op-service-account-token:
    description: '1Password service account token with access to GitHub Actions secrets'
    required: true

  changeset-bin:
    description: 'The command to run the Changesets CLI'
    required: false
    default: 'pnpx @changesets/cli'

runs:
  using: composite
  steps:
    - name: Set up Git
      id: setup-git
      uses: ./.github/actions/setup-git
      with:
        op-service-account-token: ${{ inputs.op-service-account-token }}
        permission-contents: 'write'

    - name: Checkout code
      uses: actions/checkout@v6
      with:
        clean: true
        fetch-depth: 0
        persist-credentials: false
        token: ${{ steps.setup-git.outputs.token }}

    - name: Create release tags
      id: create-tags
      shell: bash
      # language=bash
      run: |
        ${{ inputs.changeset-bin }} tag
        git pull --rebase
        git push --follow-tags
