name: Turbo Run
description: Run Turbo task with controlled concurrency and no telemetry

inputs:
  task:
    description: 'The Turbo task to run'
    required: true

  concurrency:
    description: 'Controls number of Turbo tasks running in parallel'
    required: false
    default: '10'

  turbo-bin:
    description: 'The command to run the Turbo CLI'
    required: false
    default: 'pnpx turbo'

runs:
  using: composite
  steps:
    - name: Run Turbo task
      shell: bash
      env:
        TURBO_CONCURRENCY: ${{ inputs.concurrency }}
        TURBO_TELEMETRY_DISABLED: 1
      run: ${{ inputs.turbo-bin }} run ${{ inputs.task }}
